### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by muinmomin** [MJA-CodePath/Homie#1]
We have finished the first sprint (1/3). The major part of this was the backend and the layout and setting up layout. We had never used firebase before, so it was something new that we all had to learn. /cc @codepathreview

**Comment by minhchau273** [comment]
:+1: Great job on the first implementation sprint! The app is really starting to come together. There are 2 weeks left to complete all of the required stories so that you have an MVP (minimum viable product). The purpose of this is to get the minimum set of functionality implemented first and then focus on adding in optionals afterwards. This ensures you have all the basics in place before adding in the additionals and polish.
Please consider regularly updating your README file so you have a better idea of what's left to do.
